services:
  # === Бэкенд (работает с обоими профилями) ===
  backend:
    image: ghcr.io/alex-ven/film-backend:latest
    env_file: .env.production
    environment:
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - LOGGER_TYPE=${LOGGER_TYPE}
      - LOGS_DIR=${LOGS_DIR}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network
    profiles:
      - "postgres"
      - "mongo"

  frontend:
    image: ghcr.io/alex-ven/film-frontend:latest
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - app-network   

      # === Nginx (общий для всех профилей) ===
  nginx:
    image: ghcr.io/alex-ven/film-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - frontend_dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/logs:/var/log/nginx
      - /var/www/certbot:/var/www/certbot
      - ./backend/public:/app/public:ro 
    depends_on:
      - backend
    networks:
      - app-network
    profiles:
      - "postgres"
      - "mongo"

# === PostgreSQL (только для профиля postgres) ===
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
    networks:
      - app-network
    profiles:
      - "postgres"

  # === MongoDB (только для профиля mongo) ===
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongodata:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
    networks:
      - app-network
    profiles:
      - "mongo"

# === PGAdmin (опционально, только для postgres) ===
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network
    profiles:
      - "postgres"

# Сети и тома
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:
  mongodata:
  frontend_dist:

