services:
  backend:
    build: .
    container_name: film-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - MONGO_URI=${DATABASE_URL}/${DATABASE_NAME}
      - MONGO_HOST=mongo
      - LOGGER_TYPE=${LOGGER_TYPE:-dev} # default to dev
      - LOGS_DIR=/app/logs
    depends_on:
      prac-postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - ./public:/app/public
      - ./logs:/app/logs:rw # монтируем директорию с логами
      - /app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prac-postgres:
    image: postgres:16-alpine
    container_name: prac-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: film-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongodata:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  mongodata: