name: Build and Publish Docker Images to GHCR

on:
  push:
    branches: [ "test-deploy" ]
  pull_request:
    branches: [ "test-deploy" ]

env:
  REGISTRY: ghcr.io
  REPO_OWNER: alex-ven

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Сборка backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/film-backend:latest
            ghcr.io/${{ github.actor }}/film-backend:${{ github.sha }}

      - name: Сборка frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/film-frontend:latest
            ghcr.io/${{ github.actor }}/film-frontend:${{ github.sha }}

      - name: Сборка nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nginx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/film-nginx:latest
            ghcr.io/${{ github.actor }}/film-nginx:${{ github.sha }}
